### ISSUE TITLE
RuntimeError: Failed to register operator torchvision::_new_empty_tensor_op.

### ISSUE THREAD

**Issue by hongrui16** [joe-siyuan-qiao/DetectoRS#27]
**I installed mmdetection and set up the environment as what [README.mmdet.md](https://github.com/joe-siyuan-qiao/DetectoRS/blob/master/README.mmdet.md)  told, i.e. PyTorch 1.4, mmcv, etc.
After that, i tried to train model(DetectoRS)) with a single GPU
python tools/train.py ${CONFIG_FILE} [optional arguments]
The error information was as following:**

_Traceback (most recent call last):
  File "tools/train.py", line 11, in <module>
    from mmcv.runner import init_dist
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/__init__.py", line 2, in <module>
    from .checkpoint import (_load_checkpoint, load_checkpoint, load_state_dict,
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 11, in <module>
    import torchvision
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torchvision/ops/__init__.py", line 13, in <module>
    _register_custom_op()
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torchvision/ops/_register_onnx_ops.py", line 51, in _register_custom_op
    register_custom_op_symbolic('torchvision::_new_empty_tensor_op', new_empty_tensor_op, _onnx_opset_version)
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 200, in register_custom_op_symbolic
    return utils.register_custom_op_symbolic(symbolic_name, symbolic_fn, opset_version)
  File "/root/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 793, in register_custom_op_symbolic
    .format(symbolic_name))
RuntimeError: Failed to register operator torchvision::_new_empty_tensor_op.                            The symbolic name must match the format Domain::Name,                            and sould start with a letter and contain only                            alphanumerical characters_

**Comment by D0ub1ePieR** [comment]
i solved this problem by change torchvision0.6.0 --> torchvision0.5.0

**Comment by hongrui16** [comment]
> i solved this problem by change torchvision0.6.0 --> torchvision0.5.0

i will try as you taught me.
many thanks

**Comment by joe-siyuan-qiao** [comment]
@hongrui16 Yes, that might solve the problem. @D0ub1ePieR Thanks for your help.
