### ISSUE TITLE
Wrong questions in training

### ISSUE THREAD

**Issue by xioayezi6555** [joe-siyuan-qiao/DetectoRS#30]
Training 👍: 
python tools/train.py /home/fw-traffic-02/DetectoRS/configs/DetectoRS/DetectoRS_mstrain_400_1200_r50_40e.py

Training set data format：

![image](https://user-images.githubusercontent.com/54101398/84751953-c1b30180-afef-11ea-8cfb-7945d8a2592a.png)

Error reporting：
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 115, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/fw-traffic-02/mmdetection/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/fw-traffic-02/mmdetection/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/fw-traffic-02/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 158, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'RecursiveFeaturePyramid is not in the detector registry'

Please help me to solve the problem, thank you

**Comment by betaarnsburg** [comment]
I met the problem similarly. I got the reason but I have not yet solved the problem. Because as the official installation of mmdetection, it does not includes rfp.py. Compared to DetectoRS in this repo, there are many different files from the official open-mmlab. However, for this repo there are also some problems during the installation, such as the version match of cuda. I am not sure which cuda the author used.

To solve your problem, I suggest to install the mmdetection with this repo instead of open-mmlab.

**Comment by joe-siyuan-qiao** [comment]
@xioayezi6555 yes, it's likely that you didn't install this repo so python found another mmdet instead which does not have RFP registered. @betaarnsburg Thanks for your help.

**Comment by xioayezi6555** [comment]
> I met the problem similarly. I got the reason but I have not yet solved the problem. Because as the official installation of mmdetection, it does not includes rfp.py. Compared to DetectoRS in this repo, there are many different files from the official open-mmlab. However, for this repo there are also some problems during the installation, such as the version match of cuda. I am not sure which cuda the author used.
> 
> To solve your problem, I suggest to install the mmdetection with this repo instead of open-mmlab.

Can you provide an installation instruction and warehouse address, thank you
