### ISSUE TITLE
How can we do detection with our own dataset without mask and seg

### ISSUE THREAD

**Issue by lgldl** [joe-siyuan-qiao/DetectoRS#32]
when we use our own dataset to train the DetectoRS, the error occured. our dataset have not mask, and we only want to do detectio, how can we do that?

**Comment by joe-siyuan-qiao** [comment]
Please checkout the mmdetv2 branch which supports detectors that do not output masks.

**Comment by lgldl** [comment]
> Please checkout the mmdetv2 branch which supports detectors that do not output masks.
Thank you for your reply, can you tell us how to get mmdev2? we can not find it.

**Comment by lgldl** [comment]
when we use mmdev2 to do detection task, the error occured, can you tell me how to solve it?
the error is as follows:
Traceback (most recent call last):
  File "/home/lgl/PycharmProjects/DetectoRS-mmdetv2/train_crossing.py", line 148, in <module>
    main()
  File "/home/lgl/PycharmProjects/DetectoRS-mmdetv2/train_crossing.py", line 144, in main
    meta=meta)
  File "/home/lgl/PycharmProjects/DetectoRS-mmdetv2/mmdet/apis/train.py", line 116, in train_detector
    seed=cfg.seed) for ds in dataset
  File "/home/lgl/PycharmProjects/DetectoRS-mmdetv2/mmdet/apis/train.py", line 116, in <listcomp>
    seed=cfg.seed) for ds in dataset
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/mmcv/utils/config.py", line 324, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/mmcv/utils/config.py", line 36, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'
