### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

### ISSUE THREAD

**Issue by lgldl** [joe-siyuan-qiao/DetectoRS#34]
when we use mmdetv2 to do detection task, the error occured, can you tell me how to do it?

the error is as follows:
Traceback (most recent call last):
  File "/home/lgl/PycharmProjects/DetectoRS-mmdetv2/train_crossing.py", line 148, in <module>
    main()
  File "/home/lgl/PycharmProjects/DetectoRS-mmdetv2/train_crossing.py", line 144, in main
    meta=meta)
  File "/home/lgl/PycharmProjects/DetectoRS-mmdetv2/mmdet/apis/train.py", line 116, in train_detector
    seed=cfg.seed) for ds in dataset
  File "/home/lgl/PycharmProjects/DetectoRS-mmdetv2/mmdet/apis/train.py", line 116, in <listcomp>
    seed=cfg.seed) for ds in dataset
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/mmcv/utils/config.py", line 324, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/mmcv/utils/config.py", line 36, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'

**Comment by joe-siyuan-qiao** [comment]
This looks like a mmdetection problem. Sorry, but I have no idea how it happened.
