### ISSUE TITLE
KeyError: 'ConvWS is already registered in conv layer'

### ISSUE THREAD

**Issue by yangshudi** [joe-siyuan-qiao/DetectoRS#70]
Run train.py to train a new datasets 

Traceback (most recent call last):
  File "tools/train.py", line 14, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/user/yangshudi_DetectoRS/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/user/yangshudi_DetectoRS/mmdetection/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
  File "/home/user/yangshudi_DetectoRS/mmdetection/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/user/yangshudi_DetectoRS/mmdetection/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/user/yangshudi_DetectoRS/mmdetection/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/user/yangshudi_DetectoRS/mmdetection/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmdet.ops import nms_match
  File "/home/user/yangshudi_DetectoRS/mmdetection/mmdet/ops/__init__.py", line 2, in <module>
    from .conv_ws import ConvWS2d, conv_ws_2d
  File "/home/user/yangshudi_DetectoRS/mmdetection/mmdet/ops/conv_ws.py", line 23, in <module>
    class ConvWS2d(nn.Conv2d):
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 122, in _register
    module_class=cls, module_name=name, force=force)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 58, in _register_module
    raise KeyError(f'{module_name} is already registered '
KeyError: 'ConvWS is already registered in conv layer'

**Comment by siumai-yan** [comment]
hey, and i think this'll gonna help:

https://github.com/open-mmlab/mmdetection/issues/3249
